excluded:
  — Pods

disabled_rules:
  - trailing_whitespace

warning_threshold: 5

line_length:
  warning: 150
  error: 1000
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true

